/*******************************************************************************
* 
* The content of this file or document is CONFIDENTIAL and PROPRIETARY
* to GEO Semiconductor.  It is subject to the terms of a License Agreement 
* between Licensee and GEO Semiconductor, restricting among other things,
* the use, reproduction, distribution and transfer.  Each of the embodiments,
* including this information and any derivative work shall retain this 
* copyright notice.
* 
* Copyright 2013-2016 GEO Semiconductor, Inc.
* All rights reserved.
*
* 
*******************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mxuvc.h>
#include "assert.h"


#define PRINTF(str...)          printf(str)



static const char *opt_gpInFileName;
static const char *opt_gpDwName;

void usage(void)
{
    printf("USAGE: ldmap GridMapFileName dwObjName\n");
    printf("\t GridMapFileName -- name of file which contains grid map generated by eWarp Pro\n");
    printf("\t dwObjName -- a string, name of dewarp object.  Must be the same as the name used in JSON script, such as dewarp0, dewarp1...etc\n");
}


int main(int argc, char *argv[])
{
    int ret;
    FILE    *pInFile;
    int mapw;
    int maph;
    float *pMapx;
    float *pMapy;
    char pStr[256];
    char *ps;
    int mapType;
    int dww;
    int dwh;
    int inw;
    int inh;
    int mapN;
    int t;


    if(argc < 3)
    {
        usage();
        exit(0);
    }

    // parse command lines params here if any



    // Get input file
    opt_gpInFileName = argv[1];
    pInFile = fopen(opt_gpInFileName, "rt");
    if(pInFile == NULL)
    {
        printf("Error, unable to open file %s\n", opt_gpInFileName);
        exit(-3);
    }
    // get dw obj name
    opt_gpDwName = argv[2];
    assert(opt_gpDwName);

    // get map type
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    mapType = strtol(ps, NULL, 0);
    PRINTF("file: MapType = %d\n", mapType);
    // get map size
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    maph = strtol(ps, NULL, 0);
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    mapw = strtol(ps, NULL, 0);
    PRINTF("file: MapSize=%dx%d\n", mapw, maph);
    // Get dw size
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    dww = strtol(ps, NULL, 0);
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    dwh = strtol(ps, NULL, 0);
    PRINTF("file: DewarpSize=%dx%d\n", dww, dwh);
    // Get input size
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    inw = strtol(ps, NULL, 0);
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    inh = strtol(ps, NULL, 0);
    PRINTF("file: InputSize=%dx%d\n", inw, inh);
#if 0
     // calculate mapN
    mapN = calc_mapn(dww, mapw);
    t    = calc_mapn(dwh, maph);
    if(mapN != t)  //these 2 must be the same!
    {
        printf("Error, grid file may be invalid\n");
        exit(-5);
    }
#endif
    // read out unused fields
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);
    ps = fgets(pStr, sizeof(pStr), pInFile);
    assert(ps);



    // alloc memory for map
    pMapx = malloc(mapw * maph * sizeof(float));
    if(pMapx == NULL)
    {
        printf("Error, out of memory, MapSize=%dx%d\n", mapw, maph);
        exit(-7);
    }
    pMapy = malloc(mapw * maph * sizeof(float));
    if(pMapy == NULL)
    {
        printf("Error, out of memory, MapSize=%dx%d\n", mapw, maph);
        exit(-7);
    }


    // read map from file
    for(t = 0; t < (mapw * maph); t++)
    {
        char *pTok;
        float mapx, mapy;
        short s;
        ps = fgets(pStr, sizeof(pStr), pInFile);
//        PRINTF("%d. pStr = %s", t, pStr);
        if(ps == NULL)
        {
            printf("Error, map file is too short!\n");
            exit(-6);
        }
        pTok = strtok(pStr, " \n\t");
        assert(pTok);
        pMapx[t] = strtof(pTok, NULL);
        pTok = strtok(NULL, " \n\t");
        assert(pTok);
        pMapy[t] = strtof(pTok, NULL);
//        PRINTF("%d. (%f, %f)\n", t, pMapx[t], pMapy[t]);
    } 

    ret = ldmap_init();
    if(ret < 0)
    {
        printf("Error, system initialization failed\n");
        exit(-1);
    }


    // send map to Condor
    ret = ldmap_upload(opt_gpDwName, pMapx, pMapy, mapw, maph, inw, inh, dww, dwh);
    if(ret < 0)
    {
        printf("Error, map upload failed!\n");
        exit(-8);
    }
   
    ldmap_deinit();

    // clean up
    free(pMapx);
    free(pMapy);
    fclose(pInFile);

     return(0);
}
